<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
version="1.0">

<xsl:template match="/">
<xsl:decimal-format name="aozan" decimal-separator="." grouping-separator=" "/>

<html>
<head>
  <title><xsl:value-of select="/QCReport/RunId"/> run quality report</title>
  <style TYPE="text/css">
  	
    .score-1 {
    }
    .score0 {
      background: #F34545;
    }
    .score1 {
      background: #F34545;
    }
    .score2 {
      background: #F34545;
    }
    .score3 {
      background: #F34545;
    }
    .score4 {
      background: #F8F848;
    }
    .score5 {
      background: #F8F848;
    }
    .score6 {
      background: #55D486;
    }
    .score7 {
      background: #55D486;
    }
    .score8 {
      background: #55D486;
    }
    .score9 {
      background: #55D486;
    }
    
   tr:hover {
      z-index:2;
      box-shadow:0 0 20px rgba(0, 0, 0, 1);
      background:#F6F6B4;
    }
      
    td {
      text-align: center;
      width: 100px;
      border: 1px solid black;
      
      padding-left:3px;
      padding-right:3px;
      padding-top:1px;
      padding-bottom:1px;
      position : static;
      background-clip: padding-box;
    }
    
    td.repeat {
      background: WhiteSmoke ;
      color: Gray;
      font-style: italic;
      font-size: 80%;
    }
    
    th {
        background-color:#E7EAF1;
        color:black;
        border: thin solid black;
        border-bottom-width: 2px;
        width: 50px;
        font-size: 100%;
    }
    table {
        border: medium solid #000000;
        font-size: 95%;
        border-collapse:collapse;
    }
    
    
    body{
        font-family: sans-serif;   
        font-size: 80%;
        margin-left:0px;
        margin-right:0px;
        margin-top: 0px;
        margin-bottom: 0px;
    }
    h1{
        color: #234CA5;
        font-style : italic;
        font-size : 20px;
    }
    h2{}
    h3{
        color:black;
        font-style : italic;
    }
     a:link {
        color:#1B65AF;
        font-weight: bold;
    } 
    a:visited {
        color:#1B65AF;
        font-weight: bold;
    }   
  	
  div.report {
    display:block;
    position:absolute;
    width:100%;
    top:6em;
    bottom:5px;
    left:0;
    right:0;
    padding:0 0 0 1em;
    background-color: white;
  }
	
  div.footer {
    background-color: #C1C4CA;
    border:0;
    margin:0;
    padding:0.5em;
    height: 1.3em;
    overflow:hidden;
    font-size: 100%;
    font-weight: bold;
    position:fixed;
    bottom:0;
    width:100%;
    z-index:2;
  }
        
    
    div.header {
		background-color: #C1C4CA;
        border:0;
        margin:0;
        padding: 0.5em;
        font-size: 175%;
        font-weight: bold;
        width:100%;
        height: 2em;
        position: fixed;
        vertical-align: middle;
        z-index:2;
        
    }
    
    #header_title {
        display:inline-block;
        float:left;
        clear:left;
    }
    #header_filename {
        display:inline-block;
        float:right;
        clear:right;
        font-size: 55%;
        margin-right:2em;
        text-align: right;
        vertical-align:middle;
    }

    div.header h3 {
        font-size: 50%;
        margin-bottom: 0;
    }
  	img {
  		width: 150px;
  	}
  </style>
</head>
<body>

<div class="header">
	<div id="header_title">
		<img src="http://www.transcriptome.ens.fr/aozan/images/logo_aozan_qc.png" alt="Aozan"/>  
		&#xA0;&#xA0;Quality report on run <xsl:value-of select="/QCReport/RunId"/> 
	</div> 

	<div id="header_filename">
		Generated <xsl:value-of select="/QCReport/ReportDate"/><br/>
		<a href="#lane">Lanes</a> / <a href="#sample">Samples</a>
	</div>
	
</div>

<div class="report">
  <ul>
    <li><b>Run Id: </b> <xsl:value-of select="/QCReport/RunId"/></li>
    <li><b>Flow cell: </b> <xsl:value-of select="/QCReport/FlowcellId"/></li>
    <li><b>Run started: </b> <xsl:value-of select="/QCReport/RunDate"/></li>
    <li><b>Instrument S/N: </b> <xsl:value-of select="/QCReport/InstrumentSN"/></li>
    <li><b>Instrument run number: </b> <xsl:value-of select="/QCReport/InstrumentRunNumber"/></li>
    <li><b>Generated by: </b> <xsl:value-of select="/QCReport/GeneratorName"/> version <xsl:value-of select="/QCReport/GeneratorVersion"/> 
    	(revision <xsl:value-of select="/QCReport/GeneratorRevision"/>)</li>
    <li><b>Creation date: </b> <xsl:value-of select="/QCReport/ReportDate"/></li>
  </ul>

  <a name="lane"/>
  <h2>Lanes Quality report</h2>

  <xsl:for-each select="/QCReport/ReadsReport/Reads/Read">
    <h3>Read <xsl:value-of select="@number"/> (<xsl:value-of select="@cycles"/> cycles<xsl:if test="@indexed='true'">, index</xsl:if>)</h3>
    <table>
    <tr>
      <th>Lane</th>
      <xsl:for-each select="/QCReport/ReadsReport/Columns/Column">
        <th><xsl:value-of select="."/><xsl:if test="@unit!=''"> (<xsl:value-of select="@unit"/>)</xsl:if></th>
      </xsl:for-each>
    </tr>
    <xsl:for-each select="Lane">
      <tr>
       <td><xsl:value-of select="@number"/></td>
       <xsl:for-each select="Test">
         <td class="score{@score}">
           <xsl:if test="@type='int'"><xsl:value-of select="format-number(.,'### ### ### ### ###','aozan')"/></xsl:if>
           <xsl:if test="@type='float'"><xsl:value-of select="format-number(.,'### ### ### ##0.00','aozan')"/></xsl:if>
           <xsl:if test="@type='percent'"><xsl:value-of select="format-number(.,'#0.00%','aozan')"/></xsl:if>
           <xsl:if test="@type='string'"><xsl:value-of select="."/></xsl:if>
           <xsl:if test="@type='url'"><a href="{.}">link</a></xsl:if>
         </td>
       </xsl:for-each>
     </tr>
    </xsl:for-each>

   </table>
  </xsl:for-each>

<a name="sample"/>
  <h2>Samples Quality report</h2>

  <xsl:for-each select="/QCReport/SamplesReport/Reads/Read">
    <h3>Read <xsl:value-of select="@number"/></h3>
    <table>
    <tr>
      <th>Lane</th>
      <th>Sample name</th>
      <th>Description</th>
      <th>Index</th>
      <th>Project</th>
      <xsl:for-each select="/QCReport/SamplesReport/Columns/Column">
        <th><xsl:value-of select="."/><xsl:if test="@unit!=''"> (<xsl:value-of select="@unit"/>)</xsl:if></th>
      </xsl:for-each>
      <th>Sample name</th>
    </tr>
    <xsl:for-each select="Sample">
      <tr>
       <td><xsl:value-of select="@lane"/></td>
       <td><xsl:value-of select="@name"/></td>
       <td><xsl:value-of select="@desc"/></td>
       <td><xsl:value-of select="@index"/></td>
       <td><xsl:value-of select="@project"/></td>
       <xsl:for-each select="Test">
         <td class="score{@score}">
           <xsl:if test="@type='int'"><xsl:value-of select="format-number(.,'### ### ### ### ###','aozan')"/></xsl:if>
           <xsl:if test="@type='float'"><xsl:value-of select="format-number(.,'### ### ### ##0.00','aozan')"/></xsl:if>
           <xsl:if test="@type='percent'"><xsl:value-of select="format-number(.,'#0.00%','aozan')"/></xsl:if>
           <xsl:if test="@type='string'"><xsl:value-of select="."/></xsl:if>
           <xsl:if test="@type='url'"><a href="{.}">link</a></xsl:if>
         </td>
       </xsl:for-each>
       
       <!-- Repeat Sample Name in last column -->
        <td class="repeat"><xsl:value-of select="@name"/><br/><xsl:value-of select="@project"/></td>
       </tr>
     
    </xsl:for-each>

	<!-- Repeat header columns at last row -->
	<tr >
      <td class="repeat">Lane</td>
      <td class="repeat">Sample name</td>
      <td class="repeat">Description</td>
      <td class="repeat">Index</td>
      <td class="repeat">Project</td>
      <xsl:for-each select="/QCReport/SamplesReport/Columns/Column">
        <td class="repeat"><xsl:value-of select="."/><xsl:if test="@unit!=''"> (<xsl:value-of select="@unit"/>)</xsl:if></td>
      </xsl:for-each>
      <td class="repeat">Sample_Project name</td>
    </tr>
    
   </table>
  </xsl:for-each>
<p>End QC report</p>
<!-- End div report -->
</div>

<div class="footer">
	Generated by  
	<xsl:element name="a">
		<xsl:attribute name="href"><xsl:value-of select="/QCReport/GeneratorWebsite"/></xsl:attribute>Aozan</xsl:element>
	(version <xsl:value-of select="/QCReport/GeneratorVersion"/>)
	
</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>