/*
 *                  Aozan development code
 *
 * This code may be freely distributed and modified under the
 * terms of the GNU General Public License version 3 or later 
 * and CeCILL. This should be distributed with the code. If you 
 * do not have a copy, see:
 *
 *      http://www.gnu.org/licenses/gpl-3.0-standalone.html
 *      http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
 *
 * Copyright for this code is held jointly by the Genomic platform
 * of the Institut de Biologie de l'École Normale Supérieure and
 * the individual authors. These should be listed in @author doc
 * comments.
 *
 * For more information on the Aozan project and its aims,
 * or to join the Aozan Google group, visit the home page at:
 *
 *      http://www.transcriptome.ens.fr/aozan
 *
 */

package fr.ens.transcriptome.aozan.collectors;

import java.io.File;
import java.util.logging.Logger;

import fr.ens.transcriptome.aozan.AozanException;
import fr.ens.transcriptome.aozan.Globals;
import fr.ens.transcriptome.aozan.RunData;
import fr.ens.transcriptome.aozan.io.FastqStorage;

abstract class AbstractFastqProcessThread implements Runnable {

  /** Logger */
  private static final Logger LOGGER = Logger.getLogger(Globals.APP_NAME);

  protected final File[] fastqFiles;
  protected final String projectName;
  protected final String sampleName;
  protected final int lane;
  protected final int read;
  
  protected final RunData results;
  protected final FastqStorage fastqStorage;

  protected AozanException exception;
  protected boolean success;

  /**
   * Get the results of the FastQC analysis.
   * @return a RunData object with only the result of the thread
   */
  public RunData getResults() {

    return this.results;
  }

  /**
   * Get the exception generated by the call to processSequences in the run()
   * method.
   * @return a exception object or null if no Exception has been thrown
   */
  public Exception getException() {

    return this.exception;
  }

  /**
   * Test if the call to run method was a success
   * @return true if the call to run method was a success
   */
  public boolean isSuccess() {

    return this.success;
  }

  //
  // Constructor
  //

  public AbstractFastqProcessThread(final File[] fastqFiles, final int read,
      final int lane, String projectName, final String sampleName) throws AozanException {

    if (fastqFiles == null || fastqFiles.length == 0)
      throw new AozanException("No fastq file defined");
    
    this.fastqFiles = fastqFiles;

    this.projectName = projectName;
    this.sampleName = sampleName;
    this.lane = lane;
    this.read = read;
    
    this.results = new RunData();
    
    this.fastqStorage = FastqStorage.getInstance("");

  }
}
